# Use an official Python runtime as the parent image
FROM python:3.8
# Set the working directory in the container to /app
WORKDIR /app
# Copy the current directory contents into the container at /app
COPY . /app

RUN pip install gdown
# Télécharger le dataset depuis Google Drive
RUN gdown --id '1BdCAAaWpiLlqZUr6lRPIQ3BJLiFJx_nW' --output MLP-20M.zip

# Vérifier la taille du fichier ZIP
RUN ls -lh MLP-20M.zip
# Tenter de dézipper le fichier, imprimer les erreurs s'il y en a
RUN apt-get update && apt-get install -y unzip
RUN unzip MLP-20M.zip || echo "Erreur lors de la décompression"

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements_gradio.txt
# Make port 7860 available to the world outside this container
# Gradio by default runs on port 7860
EXPOSE 7860
# Run the Gradio app when the container launches
CMD ["python", "gradio_webapp.py"]
